apiVersion: v1
kind: PersistentVolume
metadata:
  name:  "backup-mysql-instance-pv"
  labels:
    pv-usage: "backup-mysql-instance"
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv-backup/
 
