apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "backup-mysql-instance-pvc"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  selector:
    matchLabels:
      pv-usage: "backup-mysql-instance"
