apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jane_admin
  namespace: dev
subjects:
- kind: ServiceAccount
  name: jane # имя чувствительно к регистру
roleRef:
  kind: Role # явно указываем Role или ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
