apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jane_admin
  namespace: dev
subjects:
- kind: User # Group, ServiceAccount
  name: jane # имя чувствительно к регистру
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole # явно указываем Role или ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
