apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ken_view
  namespace: dev
subjects:
- kind: User # Group, ServiceAccount
  name: ken # имя чувствительно к регистру
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole # явно указываем Role или ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
