apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-iscsi
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-storage
  iscsi:
     targetPortal: 10.127.0.13:3261
     iqn: iqn.2003-01.org.linux-iscsi.instance-4.x8664:sn.7fe91425ce4b
     lun: 0
     fsType: 'ext4'
     readOnly: false
