environments:
  develop:
    values:
      - domain: develop.34.69.15.120.nip.io
  production:
    values:
      - domain: 34.69.15.120.nip.io


repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: jetstack
  url: https://charts.jetstack.io
- name: harbor
  url: https://helm.goharbor.io


templates:
  template: &template
    missingFileHandler: Info
    values:
    - ./values/{{`{{ .Release.Name }}`}}.yaml.gotmpl

releases:
- name: nginx-ingress
  chart: stable/nginx-ingress
  version: 1.11.1
  namespace: nginx-ingress

- name: cert-manager
  chart: jetstack/cert-manager
  version: 0.9.0
  namespace: cert-manager

- name: harbor
  chart: harbor/harbor
  version: 1.1.2
  namespace: harbor
  <<: *template
